---
- name: Playbook para deixar os servicos apache e ftp ativados e habilitados no boot
  hosts: webservers

  tasks:

    - name: Ativando os Serviços em maquinas RedHat Like
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - httpd
        - vsftpd
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ativando os serviços em maquinas Debian Like
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - apache2
        - proftpd
      when: ansible_facts['os_family'] == "Debian"

    - name: Ativando os Serviços em maquinas Rocky Like
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - httpd
        - vsftpd
      when: ansible_facts['os_family'] == "Rocky"