---
- name: Instalando o apache e um serviço ftp
  hosts: webservers

  tasks:

    - name: Instalando o Apache e o FTP nas distros Debian Like
      apt:
        name: "{{item}}"
        state: latest
        update_cache: true
      with_items:
        - apache2
        - proftpd
        - php
        - php-xml
        - libapache2-mod-php
      when: ansible_facts['os_family'] == "Debian"

    - name: Instalando o Apache e o FTP nas distros RedHat Like
      yum:
        name: "{{item}"
        state: latest
        update_cache: true
      with_items:
        - httpd
        - vsftpd
      when: ansible_facts['os_family'] == "RedHat"

    - name: Instalando o Apache e o FTP nas distros RedHat Like
      dnf:
        name: "{{item}"
        state: latest
        update_cache: true
      with_items:
        - httpd
        - vsftpd
      when: ansible_facts['os_family'] == "Rocky"